com:
  nxs:
    blog:
      name: 程序猿DD
      title: Spring Boot教程
      desc: ${com.nxs.blog.name}正在努力写《${com.nxs.blog.title}》
      value: ${random.value} # 随机字符串 ex: 0d2a9b13f987fef784584cbedcd4f758
      number: ${random.int} # 随机int
      bignumber: ${random.long} # 随机long
      test1: ${random.int(10)} # 10以内的随机数
      test2: ${random.int[10,20]} # 10-20的随机数
